# permissions for end users to view nextclouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextcloud-viewer-role
rules:
- apiGroups:
  - operators.nsk.io
  resources:
  - nextclouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.nsk.io
  resources:
  - nextclouds/status
  verbs:
  - get
